		SELECT			UNIQUE_ID, CUSIP, MATURITY, ASOF_DATE
		INTO			#CPCUSIP
		FROM			dbo.T_BRS_SEC
		WHERE			RTRIM(SM_SEC_GROUP) + '_' + RTRIM(SM_SEC_TYPE) IN ('CASH_CP','CASH_TBILL','CASH_AGENCY')
		AND				CUSIP NOT LIKE 'B%'
		AND				CUSIP NOT LIKE '99%'
		AND				LEN(CUSIP) < 10
		AND				year(MATURITY) <= @CutoffYear