--Warnings
--ALTER VIEW [dbo].[REP_ALL_SOURCE_FLDS] AS 
SELECT  
    OPB_SUBJECT.SUBJ_NAME          PARENT_SUBJECT_AREA,  
    OPB_SUBJECT.SUBJ_ID            PARENT_SUBJECT_ID,  
    OPB_SRC.SOURCE_NAME            PARENT_SOURCE_NAME,  
    OPB_SRC.BUSINESS_NAME          PARENT_SOURCE_BUSINESS_NAME,  
    OPB_SRC.SRC_ID                 PARENT_SOURCE_ID,  
    OPB_SRC.SRC_DESC               PARENT_SOURCE_DESCRIPTION,
    OPB_SRC.VERSION_NUMBER         PARENT_SOURCE_VERSION_NUMBER,  
    OPB_SRC.VERSION_STATUS         PARENT_SOURCE_VERSION_STATUS,  
    OPB_SRC.UTC_CHECKIN            PARENT_SOURCE_UTC_CHECKIN,
    OPB_SRC.UTC_LAST_SAVED         PARENT_SOURCE_UTC_LAST_SAVED,
    OPB_SRC.LAST_SAVED             PARENT_SOURCE_LAST_SAVED,
    OPB_DBD.SRCTYPE                PARENT_SOURCE_TYPE,  
    OPB_DBD.DBDNAM                 PARENT_SOURCE_DATABASE_NAME,  
    OPB_MMD_DBTYPE.DBTYPE_NAME     PARENT_SOURCE_DATABASE_TYPE,  
    OPB_SUBJECT.SUBJ_NAME          SUBJECT_AREA,  
    OPB_SUBJECT.SUBJ_ID            SUBJECT_ID, 
    OPB_SRC.SOURCE_NAME            SOURCE_NAME,  
    OPB_SRC.SRC_ID                 SOURCE_ID,  
    OPB_SRC.SRC_DESC               SOURCE_DESCRIPTION,
    OPB_SRC.VERSION_NUMBER         SOURCE_VERSION_NUMBER,
    OPB_SRC.VERSION_STATUS         SOURCE_VERSION_STATUS,
    OPB_SRC.UTC_CHECKIN            SOURCE_UTC_CHECKIN,
    OPB_SRC.UTC_LAST_SAVED         SOURCE_UTC_LAST_SAVED,
    OPB_SRC.LAST_SAVED             SOURCE_LAST_SAVED,
    OPB_DBD.DBDNAM                 SOURCE_DATABASE_NAME,
    OPB_SRC_FLD.SRC_NAME           SOURCE_FIELD_NAME,  
    OPB_SRC_FLD.BUSINESS_NAME      SOURCE_FIELD_BUSINESS_NAME,  
    OPB_SRC_FLD.FLDID              SOURCE_FIELD_ID,  
    OPB_SRC_FLD.SRC_DESC           SOURCE_FIELD_DESCRIPTION,  
    OPB_SRC_FLD.FLDNO              SOURCE_FIELD_NUMBER,
    OPB_SRC_FLD.NXTSIBID           SOURCE_FIELD_NEXT_FIELD_ID,
    OPB_SRC_FLD.FLDLVL             SOURCE_FIELD_LEVEL,
    OPB_SRC_FLD.PICTXT             SOURCE_FIELD_PICTURE_TEXT,
    OPB_SRC_FLD.OCCTIMES           SOURCE_FIELD_OCCURS_TIMES,
    OPB_SRC_FLD.REDFNAME           SOURCE_FIELD_REDEFINES_FIELD,
    OPB_SRC_FLD.OFFS               SOURCE_FIELD_DISPLAY_OFFSET,
    OPB_SRC_FLD.LEN                SOURCE_FIELD_DISPLAY_LENGTH,
    OPB_SRC_FLD.POFFS              SOURCE_FIELD_PHYSICAL_OFFSET,
    OPB_SRC_FLD.PLEN               SOURCE_FIELD_PHYSICAL_LENGTH,
    OPB_SRC_FLD.NXTCHLDID          SOURCE_FIELD_CHILD_FIELD_ID,
    REP_SRC_KEY_TYPES.KEYTYPE_NAME SOURCE_FIELD_KEY_TYPE,  
    REP_FLD_DATATYPE.DTYPE_NAME    SOURCE_FIELD_DATATYPE,  
    OPB_PICDSC.SRC_PREC            SOURCE_FIELD_PRECISION,  
    OPB_PICDSC.SRC_SCALE           SOURCE_FIELD_SCALE,  
    REP_PIC_USAGE.USAGE_NAME       SOURCE_FIELD_PIC_USAGE_NAME,
    OPB_SRC_FLD.NULLTYPE           SOURCE_FIELD_NULLTYPE,  
    NULL                           REPOSITORY_NAME,  
    0                              IS_SHORTCUT,  
    0                              IS_GLOBAL_SHORTCUT
FROM  
    OPB_SUBJECT, OPB_SRC, OPB_DBD, OPB_MMD_DBTYPE, OPB_SRC_FLD,  
    REP_FLD_DATATYPE, OPB_PICDSC, REP_SRC_KEY_TYPES, REP_PIC_USAGE
WHERE  
    OPB_SRC.SUBJ_ID = OPB_SUBJECT.SUBJ_ID 
    AND OPB_SRC.SUBJ_ID = OPB_DBD.SUBJ_ID
    AND OPB_SRC.SRC_ID = OPB_SRC_FLD.SRC_ID 
    AND OPB_SRC_FLD.PICID = OPB_PICDSC.PICID 
    AND OPB_SRC_FLD.KEYTYPE = REP_SRC_KEY_TYPES.KEYTYPE_NUM 
    AND OPB_SRC.DBDID = OPB_DBD.DBDID
    AND OPB_DBD.DBTYPE = OPB_MMD_DBTYPE.DBTYPE_ID 
    AND OPB_SRC_FLD.IS_HIDDEN = 0 
    AND OPB_PICDSC.SRC_NTYPE = REP_FLD_DATATYPE.DTYPE_NUM 
    AND OPB_SRC.VERSION_NUMBER = OPB_DBD.VERSION_NUMBER 
    AND OPB_SRC.VERSION_NUMBER = OPB_SRC_FLD.VERSION_NUMBER 
    AND OPB_SRC.VERSION_NUMBER = OPB_PICDSC.VERSION_NUMBER 
    AND OPB_SRC.IS_VISIBLE = 1
    AND OPB_PICDSC.PIC_USAGE % 16 = REP_PIC_USAGE.USAGE_NUM
    AND NOT EXISTS (SELECT '1' FROM OPB_SHORTCUT, OPB_SHORTCUT DBD  
    WHERE OPB_SRC.SRC_ID = OPB_SHORTCUT.OBJECT_ID  
      AND OPB_SRC.SUBJ_ID = OPB_SHORTCUT.SUBJECT_ID  
      AND OPB_SHORTCUT.OBJECT_TYPE = 25
      AND OPB_SHORTCUT.IS_VISIBLE = 1
      AND OPB_SHORTCUT.PARENT_ID = DBD.OBJECT_ID
      AND OPB_SHORTCUT.SUBJECT_ID = DBD.SUBJECT_ID
      AND OPB_SHORTCUT.VERSION_NUMBER = DBD.VERSION_NUMBER
      AND NOT (OPB_SHORTCUT.SHORTCUT_NAME = DBD.SHORTCUT_NAME)
      AND DBD.OBJECT_TYPE = 22)  
UNION ALL
SELECT  
    PARENT.SUBJ_NAME               PARENT_SUBJECT_AREA,  
    PARENT.SUBJ_ID                 PARENT_SUBJECT_ID,  
    OPB_SRC.SOURCE_NAME            PARENT_SOURCE_NAME,  
    OPB_SRC.BUSINESS_NAME          PARENT_SOURCE_BUSINESS_NAME,  
    OPB_SRC.SRC_ID                 PARENT_SOURCE_ID,  
    OPB_SRC.SRC_DESC               PARENT_SOURCE_DESCRIPTION,
    OPB_SRC.VERSION_NUMBER         PARENT_SOURCE_VERSION_NUMBER,  
    OPB_SRC.VERSION_STATUS         PARENT_SOURCE_VERSION_STATUS,  
    OPB_SRC.UTC_CHECKIN            PARENT_SOURCE_UTC_CHECKIN,
    OPB_SRC.UTC_LAST_SAVED         PARENT_SOURCE_UTC_LAST_SAVED,
    OPB_SRC.LAST_SAVED             PARENT_SOURCE_LAST_SAVED,
    OPB_DBD.SRCTYPE                PARENT_SOURCE_TYPE,  
    OPB_DBD.DBDNAM                 PARENT_SOURCE_DATABASE_NAME,  
    OPB_MMD_DBTYPE.DBTYPE_NAME     PARENT_SOURCE_DATABASE_TYPE,  
    CHILD.SUBJ_NAME                SUBJECT_AREA,  
    CHILD.SUBJ_ID                  SUBJECT_ID,  
    OPB_SHORTCUT.SHORTCUT_NAME     SOURCE_NAME,  
    OPB_SHORTCUT.OBJECT_ID         SOURCE_ID,  
    OPB_SHORTCUT.COMMENTS          SOURCE_DESCRIPTION,
    OPB_SHORTCUT.VERSION_NUMBER    SOURCE_VERSION_NUMBER,
    OPB_SHORTCUT.VERSION_STATUS    SOURCE_VERSION_STATUS,
    OPB_SHORTCUT.UTC_CHECKIN       SOURCE_UTC_CHECKIN,
    OPB_SHORTCUT.UTC_LAST_SAVED    SOURCE_UTC_LAST_SAVED,
    OPB_SHORTCUT.CREATION_TIME     SOURCE_LAST_SAVED, 
    DBD.SHORTCUT_NAME              SOURCE_DATABASE_NAME,
    OPB_SRC_FLD.SRC_NAME           SOURCE_FIELD_NAME,  
    OPB_SRC_FLD.BUSINESS_NAME      SOURCE_FIELD_BUSINESS_NAME,  
    OPB_SRC_FLD.FLDID              SOURCE_FIELD_ID,  
    OPB_SRC_FLD.SRC_DESC           SOURCE_FIELD_DESCRIPTION,  
    OPB_SRC_FLD.FLDNO              SOURCE_FIELD_NUMBER,
    OPB_SRC_FLD.NXTSIBID           SOURCE_FIELD_NEXT_FIELD_ID,
    OPB_SRC_FLD.FLDLVL             SOURCE_FIELD_LEVEL,
    OPB_SRC_FLD.PICTXT             SOURCE_FIELD_PICTURE_TEXT,
    OPB_SRC_FLD.OCCTIMES           SOURCE_FIELD_OCCURS_TIMES,
    OPB_SRC_FLD.REDFNAME           SOURCE_FIELD_REDEFINES_FIELD,
    OPB_SRC_FLD.OFFS               SOURCE_FIELD_DISPLAY_OFFSET,
    OPB_SRC_FLD.LEN                SOURCE_FIELD_DISPLAY_LENGTH,
    OPB_SRC_FLD.POFFS              SOURCE_FIELD_PHYSICAL_OFFSET,
    OPB_SRC_FLD.PLEN               SOURCE_FIELD_PHYSICAL_LENGTH,
    OPB_SRC_FLD.NXTCHLDID          SOURCE_FIELD_CHILD_FIELD_ID,
    REP_SRC_KEY_TYPES.KEYTYPE_NAME SOURCE_FIELD_KEY_TYPE, 
    REP_FLD_DATATYPE.DTYPE_NAME    SOURCE_FIELD_DATATYPE,  
    OPB_PICDSC.SRC_PREC            SOURCE_FIELD_PRECISION,  
    OPB_PICDSC.SRC_SCALE           SOURCE_FIELD_SCALE, 
    REP_PIC_USAGE.USAGE_NAME       SOURCE_FIELD_PIC_USAGE_NAME,
    OPB_SRC_FLD.NULLTYPE           SOURCE_FIELD_NULLTYPE,  
    OPB_SHORTCUT.REPOSITORY_NAME   REPOSITORY_NAME,  
    1                              IS_SHORTCUT,  
    0                              IS_GLOBAL_SHORTCUT
FROM  
    OPB_SHORTCUT, OPB_SUBJECT PARENT, OPB_SUBJECT CHILD, 
    OPB_SRC, OPB_DBD, OPB_MMD_DBTYPE, OPB_SRC_FLD,  
    REP_FLD_DATATYPE, OPB_PICDSC, REP_SRC_KEY_TYPES, OPB_SHORTCUT DBD, REP_PIC_USAGE
WHERE  
    OPB_SHORTCUT.OBJECT_ID = OPB_SRC.SRC_ID 
    AND OPB_SHORTCUT.SUBJECT_ID = CHILD.SUBJ_ID 
    AND OPB_SHORTCUT.REFERENCE_TYPE = 1 
    AND OPB_SHORTCUT.IS_VISIBLE = 1 
    AND OPB_SHORTCUT.OBJECT_TYPE = 25 
    AND OPB_SRC.SUBJ_ID = PARENT.SUBJ_ID 
    AND OPB_SRC.SRC_ID = OPB_SRC_FLD.SRC_ID 
    AND OPB_SRC.DBDID = OPB_DBD.DBDID 
    AND OPB_SRC_FLD.PICID = OPB_PICDSC.PICID 
    AND OPB_SRC_FLD.KEYTYPE = REP_SRC_KEY_TYPES.KEYTYPE_NUM 
    AND OPB_SRC_FLD.IS_HIDDEN = 0 
    AND OPB_PICDSC.SRC_NTYPE = REP_FLD_DATATYPE.DTYPE_NUM 
    AND OPB_DBD.DBTYPE = OPB_MMD_DBTYPE.DBTYPE_ID 
    AND OPB_SRC.VERSION_NUMBER = OPB_DBD.VERSION_NUMBER 
    AND OPB_SRC.VERSION_NUMBER = OPB_SRC_FLD.VERSION_NUMBER 
    AND OPB_SRC.VERSION_NUMBER = OPB_PICDSC.VERSION_NUMBER 
    AND OPB_SRC.IS_VISIBLE = 1
    AND OPB_PICDSC.PIC_USAGE % 16 = REP_PIC_USAGE.USAGE_NUM
    AND OPB_SHORTCUT.PARENT_ID = DBD.OBJECT_ID
    AND OPB_SHORTCUT.SUBJECT_ID = DBD.SUBJECT_ID
    AND OPB_SHORTCUT.VERSION_NUMBER = DBD.VERSION_NUMBER
    AND NOT (OPB_SHORTCUT.SHORTCUT_NAME = DBD.SHORTCUT_NAME)
    AND DBD.OBJECT_TYPE = 22
UNION ALL
SELECT  
    NULL                           PARENT_SUBJECT_AREA,  
    NULL                           PARENT_SUBJECT_ID,  
    NULL                           PARENT_SOURCE_NAME,  
    NULL                           PARENT_SOURCE_BUSINESS_NAME,  
    NULL                           PARENT_SOURCE_ID,  
    NULL                           PARENT_SOURCE_DESCRIPTION,  
    NULL                           PARENT_SOURCE_VERSION_NUMBER,
    NULL                           PARENT_SOURCE_VERSION_STATUS,  
    NULL                           PARENT_SOURCE_UTC_CHECKIN,
    NULL                           PARENT_SOURCE_UTC_LAST_SAVED,
    NULL                           PARENT_SOURCE_LAST_SAVED,
    NULL                           PARENT_SOURCE_TYPE,  
    NULL                           PARENT_SOURCE_DATABASE_NAME,  
    NULL                           PARENT_SOURCE_DATABASE_TYPE,  
    OPB_SUBJECT.SUBJ_NAME          SUBJECT_AREA,  
    OPB_SUBJECT.SUBJ_ID            SUBJECT_ID,  
    OPB_SHORTCUT.SHORTCUT_NAME     SOURCE_NAME,  
    OPB_SHORTCUT.OBJECT_ID         SOURCE_ID,
    OPB_SHORTCUT.COMMENTS          SOURCE_DESCRIPTION,
    OPB_SHORTCUT.VERSION_NUMBER    SOURCE_VERSION_NUMBER,
    OPB_SHORTCUT.VERSION_STATUS    SOURCE_VERSION_STATUS,
    OPB_SHORTCUT.UTC_CHECKIN       SOURCE_UTC_CHECKIN,
    OPB_SHORTCUT.UTC_LAST_SAVED    SOURCE_UTC_LAST_SAVED,
    OPB_SHORTCUT.CREATION_TIME     SOURCE_LAST_SAVED, 
    DBD.SHORTCUT_NAME              SOURCE_DATABASE_NAME,
    NULL                           SOURCE_FIELD_NAME,  
    NULL                           SOURCE_FIELD_BUSINESS_NAME,  
    NULL                           SOURCE_FIELD_ID,
    NULL                           SOURCE_FIELD_DESCRIPTION,  
    NULL                           SOURCE_FIELD_NUMBER,
    NULL                           SOURCE_FIELD_NEXT_FIELD_ID,
    NULL                           SOURCE_FIELD_LEVEL,
    NULL                           SOURCE_FIELD_PICTURE_TEXT,
    NULL                           SOURCE_FIELD_OCCURS_TIMES,
    NULL                           SOURCE_FIELD_REDEFINES_FIELD,
    NULL                           SOURCE_FIELD_DISPLAY_OFFSET,
    NULL                           SOURCE_FIELD_DISPLAY_LENGTH,
    NULL                           SOURCE_FIELD_PHYSICAL_OFFSET,
    NULL                           SOURCE_FIELD_PHYSICAL_LENGTH,
    NULL                           SOURCE_FIELD_CHILD_FIELD_ID,
    NULL                           SOURCE_FIELD_KEY_TYPE,  
    NULL                           SOURCE_FIELD_DATATYPE,  
    NULL                           SOURCE_FIELD_PRECISION,  
    NULL                           SOURCE_FIELD_SCALE,  
    NULL                           SOURCE_FIELD_PIC_USAGE_NAME,
    NULL                           SOURCE_FIELD_NULLTYPE,  
    OPB_SHORTCUT.REPOSITORY_NAME   REPOSITORY_NAME,  
    1                              IS_SHORTCUT,  
    1                              IS_GLOBAL_SHORTCUT
FROM  
    OPB_SHORTCUT, OPB_SUBJECT, OPB_SHORTCUT DBD
WHERE  
    OPB_SHORTCUT.SUBJECT_ID = OPB_SUBJECT.SUBJ_ID 
    AND OPB_SHORTCUT.REFERENCE_TYPE = 2 
    AND OPB_SHORTCUT.OBJECT_TYPE = 25 
    AND OPB_SHORTCUT.IS_VISIBLE = 1
    AND OPB_SHORTCUT.PARENT_ID = DBD.OBJECT_ID
    AND OPB_SHORTCUT.SUBJECT_ID = DBD.SUBJECT_ID
    AND OPB_SHORTCUT.VERSION_NUMBER = DBD.VERSION_NUMBER
    AND NOT (OPB_SHORTCUT.SHORTCUT_NAME = DBD.SHORTCUT_NAME)
    AND DBD.OBJECT_TYPE = 22