	SELECT
			 A.M_CNTN_N_ID AS CONN_ID,
			 A.M_CNTN_C_NAME AS CONN_NAME,
			 
			CASE A.M_CNTN_N_TYPE 
				WHEN 1 THEN 'Repository' 
				WHEN 2 THEN 'Secured' 
			END AS CONN_TYPE,
			 A.M_CNTN_C_NETNAME AS NETWORK_NAME,
			 A.M_CNTN_C_RDBMSNAME AS RDBMS_NAME,
			 CONVERT(DATETIME, CONVERT(VARCHAR(23), CONVERT(DATETIME, '15-DEC-1970') + (A.M_CNTN_N_LAD / CONVERT(FLOAT, (60 * 60 * 24))), 101) + ' ' + CONVERT(VARCHAR, CONVERT(DATETIME, '15-DEC-1970') + (A.M_CNTN_N_LAD / CONVERT(FLOAT, (60 * 60 * 24))), 108), 101) AS LAST_UPDATE_DATE
	FROM  OBJ_M_CONNECTION A 
	WHERE	 A.M_CNTN_N_LAT  != 1