	SELECT
			 B.UNIVERSE_ID AS JOIN_UNIVERSE_ID,
			 B.UNIVERSE_ID AS JOINED_FROM_TAB_UNV_ID,
			 B.TABLE_ID AS JOINED_FROM_TABLE_ID,
			 B.TAB_NAME AS JOINED_FROM_TABLE,
			 C.UNIVERSE_ID AS JOINED_TO_TAB_UNV_ID,
			 C.TABLE_ID AS JOINED_TO_TABLE_ID,
			 C.TAB_NAME AS JOINED_TO_TABLE
	FROM  UNV_JOINCONTENT A,
		 UNV_TABLE B,
		 UNV_TABLE C 
	WHERE	 (A.UNIVERSE_ID  = B.UNIVERSE_ID
	 AND	A.JN_TABLE1_ID  = B.TABLE_ID
	 AND	A.UNIVERSE_ID  = C.UNIVERSE_ID
	 AND	A.JN_TABLE2_ID  = C.TABLE_ID
	 AND	NOT (B.TABLE_ID  > 65536
	 AND	C.TABLE_ID  > 65536))
	 OR	(A.UNIVERSE_ID  = C.UNIVERSE_ID
	 AND	A.JN_TABLE1_ID  = C.TABLE_ID
	 AND	A.UNIVERSE_ID  = B.UNIVERSE_ID
	 AND	A.JN_TABLE2_ID  = B.TABLE_ID
	 AND	NOT (B.TABLE_ID  > 65536
	 AND	C.TABLE_ID  > 65536))
	UNION
	 SELECT
			 A.UNIVERSE_ID AS JOIN_UNIVERSE_ID,
			 B.UNIVERSE_ID AS JOINED_FROM_TAB_UNV_ID,
			 B.TABLE_ID AS JOINED_FROM_TABLE_ID,
			 B.TAB_NAME AS JOINED_FROM_TABLE,
			 C.UNIVERSE_ID AS JOINED_TO_TAB_UNV_ID,
			 C.TABLE_ID AS JOINED_TO_TABLE_ID,
			 C.TAB_NAME AS JOINED_TO_TABLE
	FROM  UNV_JOINCONTENT A,
		 UNV_TABLE B,
		 UNV_TABLE C 
	WHERE	 (B.TABLE_ID  > 65536
	 AND	(A.JN_TABLE1_ID + (A.UNIVERSE_ID * 65536))  = B.TABLE_ID
	 AND	(A.JN_TABLE2_ID + (A.UNIVERSE_ID * 65536))  = C.TABLE_ID
	 AND	B.UNIVERSE_ID  = C.UNIVERSE_ID)
	 OR	(C.TABLE_ID  > 65536
	 AND	(A.JN_TABLE1_ID + (A.UNIVERSE_ID * 65536))  = C.TABLE_ID
	 AND	(A.JN_TABLE2_ID + (A.UNIVERSE_ID * 65536))  = B.TABLE_ID
	 AND	B.UNIVERSE_ID  = C.UNIVERSE_ID)
	 